services:
  postgres:
    image: postgres:15
    platform: linux/amd64
    container_name: fitness_db
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
      POSTGRES_DB: fitness_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitness_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitness_user -d fitness_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: fitness-backend
    environment:
      DATABASE_URL: postgres://fitness_user:fitness_password@postgres:5432/fitness_db
      PORT: 1337
      NODE_ENV: development  # Добавляем NODE_ENV=development
      JWT_SECRET: trainer_dev_secret_ke1
    ports:
      - "1337:1337"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - fitness_network
    command: npm run dev
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  fitness_network:
    driver: bridge